### ISSUE TITLE
Implement validateInvocation

### ISSUE THREAD

**Issue by jakopako** [JupiterOne/graph-crowdstrike#84]
Currently, validateInvocation is not implemented, yet marked as TODO here: https://github.com/JupiterOne/graph-crowdstrike/blob/main/src/index.ts#L30

If nothing speaks against it, I'd like to implement this function but I wanted to check first by opening this issue before doing a pull request.

**Comment by zemberdotnet** [comment]
Hi @jakopako 👋 We're open to PRs and happy to review one if you'd like to implement this!

**Comment by jakopako** [comment]
Thanks for the explanation and the links! I'll work on this and come back if I have questions.

**Comment by zemberdotnet** [comment]
Closed by #86
